### ISSUE TITLE
Need for locking?

### ISSUE THREAD

**Issue by imduffy15** [awslabs/aws-transit-vpc#1]
What happens when two VGWs are tagged with transitvpc:spoke=true at the same time, the poller creates the necessary config files and 4 puts (two for each VGW cause we've two cisco csrs) are fired and the cisco configurator lambda function gets executed. Is there chances for a race condition where the cisco configurator will be sshed on twice to the same CSR attempting to manipulate the config?

**Comment by stevemorad** [comment]
The CSRs are configured to only allow one SSH connection at a time. So if two VGWs are tagged at the same time, the first lambda function that connects will configure the CSR. The second function will get a connection error and try again later (up to three tries). Configuration typically takes between 10-20 seconds, so the second function should be able to connect on its second try.

The Lambda FAQ has more information about failures related to Amazon S3 bucket notifications and custom events: https://aws.amazon.com/lambda/faqs/ (see question: What happens if my function fails while processing an event?)

**Comment by imduffy15** [comment]
Great thanks Steve!
