### ISSUE TITLE
How are the Routes to Spoke VPCs propagated to the Corporate DC

### ISSUE THREAD

**Issue by P13612** [awslabs/aws-transit-vpc#7]
I set up the entire infrastructur in one single dedicated account. The cloudformation script provided are fantastic. I attached a direct connect link the transit VPC. The Transit VPC has a CIDR range which is an official subnet of our corporate network, so traffic will be routed there. But now how does my corporate router know about the routes known to the Cisco CSR routers for the Spoke VPCs how do I get them. Do I have to use the BGP ASN to get them and still how are the routes eventually propagated. I don't get the concept. Can somebody help?

Regards

Peter

**Comment by stevemorad** [comment]
From a high-level, BGP is what propagates the routes from your VPCs, through the CSRs, to your corporate network.  But the details depend on how you connected your DirectConnect connection to the transit VPC.  Are you using a VGW as described in appendix 'D' of the implementation guide, or are you tunneling from your DX routers to the CSRs directly?
http://docs.aws.amazon.com/solutions/latest/cisco-based-transit-vpc/appendix-d.html

**Comment by stevemorad** [comment]
Closing issue due to how long it has been open with no response. To close out, two things come to mind here.  

First, the CSRs cannot route directly to a locally attached VGW as described initially.  The VGW either needs to establish VPN connections to the CSRs (by tagging it and, essentially, making it a spoke) or by tunneling from the customer's DX router to the CSRs.

Second, when connecting DX through a VGW that has been tagged to join the transit network, we recently updated the documentation to recommend using different ASNs for the corporate side of the network than for the transit VPC.  This will ensure corporate routes are successfully propagated all the way to the spokes.
